(lang dune 3.17)

(name Day06)

(generate_opam_files true)

(source
 (github cainytheslave/AOC2024))

(authors "John Wagner <info@techbra.in>")

(license LICENSE)

(package
 (name Day06)
 (synopsis "AOC Solution for day 06")
 (description "")
 (depends ocaml batteries))
