(lang dune 3.17)

(name Day20)

(generate_opam_files true)

(source
 (github cainytheslave/AOC2024))

(authors "John Wagner <info@techbra.in>")

(license LICENSE)

(package
 (name Day20)
 (synopsis "AOC Solution for day 20")
 (description "")
 (depends ocaml batteries))
