(lang dune 3.17)

(name Day19)

(generate_opam_files true)

(source
 (github cainytheslave/AOC2024))

(authors "John Wagner <info@techbra.in>")

(license LICENSE)

(package
 (name Day19)
 (synopsis "AOC Solution for day 19")
 (description "")
 (depends ocaml batteries))
