(lang dune 3.17)

(name Day07)

(generate_opam_files true)

(source
 (github cainytheslave/AOC2024))

(authors "John Wagner <info@techbra.in>")

(license LICENSE)

(package
 (name Day07)
 (synopsis "AOC Solution for day 07")
 (description "")
 (depends ocaml batteries))
