(lang dune 3.17)

(name Day21)

(generate_opam_files true)

(source
 (github cainytheslave/AOC2024))

(authors "John Wagner <info@techbra.in>")

(license LICENSE)

(package
 (name Day21)
 (synopsis "AOC Solution for day 21")
 (description "")
 (depends ocaml batteries))
