(lang dune 3.17)

(name Day08)

(generate_opam_files true)

(source
 (github cainytheslave/AOC2024))

(authors "John Wagner <info@techbra.in>")

(license LICENSE)

(package
 (name Day08)
 (synopsis "AOC Solution for day 08")
 (description "")
 (depends ocaml batteries))
