(lang dune 3.19)

(name Day18)

(generate_opam_files true)

(source
 (github cainytheslave/AOC2024))

(authors "John Wagner <info@techbra.in>")

(license LICENSE)

(package
 (name Day18)
 (synopsis "AOC Solution for day 18")
 (description "")
 (depends ocaml batteries))
