(lang dune 3.17)

(name Day14)

(generate_opam_files true)

(source
 (github cainytheslave/AOC2024))

(authors "John Wagner <info@techbra.in>")

(license LICENSE)

(package
 (name Day14)
 (synopsis "AOC Solution for day 14")
 (description "")
 (depends ocaml batteries))
