(lang dune 3.17)

(name Day10)

(generate_opam_files true)

(source
 (github cainytheslave/AOC2024))

(authors "John Wagner <info@techbra.in>")

(license LICENSE)

(package
 (name Day10)
 (synopsis "AOC Solution for day 10")
 (description "")
 (depends ocaml batteries))
