(lang dune 3.17)

(name Day17)

(generate_opam_files true)

(source
 (github cainytheslave/AOC2024))

(authors "John Wagner <info@techbra.in>")

(license LICENSE)

(package
 (name Day17)
 (synopsis "AOC Solution for day 17")
 (description "")
 (depends ocaml batteries))
