(lang dune 3.17)

(name Day04)

(generate_opam_files true)

(source
 (github cainytheslave/AOC2024))

(authors "John Wagner <info@techbra.in>")

(license LICENSE)

(package
 (name Day04)
 (synopsis "AOC Solution for day 04")
 (description "")
 (depends ocaml batteries))
