(lang dune 3.19)

(name Day24)

(generate_opam_files true)

(source
 (github cainydev/AOC2024))

(authors "John Wagner <info@techbra.in>")

(license LICENSE)

(package
 (name Day24)
 (synopsis "AOC Solution for day 24")
 (description "")
 (depends ocaml batteries line_oriented grid psq))
