(lang dune 3.19)

(name Day25)

(generate_opam_files true)

(source
 (github cainydev/AOC2024))

(authors "John Wagner <info@techbra.in>")

(license LICENSE)

(package
 (name Day25)
 (synopsis "AOC Solution for day 25")
 (description "")
 (depends ocaml batteries line_oriented grid psq))
