(lang dune 3.17)

(name Day15)

(generate_opam_files true)

(source
 (github cainytheslave/AOC2024))

(authors "John Wagner <info@techbra.in>")

(license LICENSE)

(package
 (name Day15)
 (synopsis "AOC Solution for day 15")
 (description "")
 (depends ocaml batteries))
