(lang dune 3.17)

(name Day09)

(generate_opam_files true)

(source
 (github cainytheslave/AOC2024))

(authors "John Wagner <info@techbra.in>")

(license LICENSE)

(package
 (name Day09)
 (synopsis "AOC Solution for day 09")
 (description "")
 (depends ocaml batteries))
