(lang dune 3.19)

(name Day16)

(generate_opam_files true)

(source
 (github cainytheslave/AOC2024))

(authors "John Wagner <info@techbra.in>")

(license LICENSE)

(package
 (name Day16)
 (synopsis "AOC Solution for day 16")
 (description "")
 (depends ocaml batteries))
